# Generated by Django 6.0.3 on 2026-04-02 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSystem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('alphabet', 'Alphabet'), ('abjad', 'Abjad'), ('abugida', 'Abugida'), ('syllabary', 'Syllabary'), ('logographic', 'Logographic'), ('other', 'Other')], max_length=20)),
                ('direction', models.CharField(max_length=10)),
                ('writing_mode', models.CharField(blank=True, max_length=20)),
                ('uses_spaces', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writing_systems', to='languages.language')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OrthographyRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('rule_type', models.CharField(choices=[('spelling', 'Spelling'), ('phoneme_mapping', 'Phoneme Mapping'), ('diacritic_usage', 'Diacritic Usage'), ('exception', 'Exception')], max_length=50)),
                ('priority', models.IntegerField(default=0)),
                ('examples', models.TextField(blank=True)),
                ('exceptions', models.TextField(blank=True)),
                ('writing_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orthography_rules', to='writing.writingsystem')),
            ],
            options={
                'ordering': ['priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ScriptSymbol',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symbol', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('symbol_type', models.CharField(choices=[('letter', 'Letter'), ('diacritic', 'Diacritic'), ('digit', 'Digit'), ('punctuation', 'Punctuation'), ('other', 'Other')], max_length=20)),
                ('uppercase', models.CharField(blank=True, max_length=10)),
                ('lowercase', models.CharField(blank=True, max_length=10)),
                ('ipa_value', models.CharField(blank=True, max_length=50)),
                ('romanization', models.CharField(blank=True, max_length=50)),
                ('unicode_representation', models.CharField(blank=True, max_length=50)),
                ('order', models.IntegerField(blank=True, null=True)),
                ('writing_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symbols', to='writing.writingsystem')),
            ],
            options={
                'ordering': ['order', 'symbol'],
                'unique_together': {('writing_system', 'symbol')},
            },
        ),
    ]
