# Generated by Django 6.0.3 on 2026-04-02 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DerivationRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('source_category', models.CharField(max_length=50)),
                ('target_category', models.CharField(max_length=50)),
                ('transformation', models.CharField(max_length=255)),
                ('semantic_effect', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivation_rules', to='languages.language')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InflectionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inflection_categories', to='languages.language')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('language', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Morpheme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=255)),
                ('morpheme_type', models.CharField(choices=[('root', 'Root'), ('prefix', 'Prefix'), ('suffix', 'Suffix'), ('infix', 'Infix'), ('circumfix', 'Circumfix')], max_length=20)),
                ('gloss', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='morphemes', to='languages.language')),
            ],
            options={
                'ordering': ['form'],
            },
        ),
        migrations.CreateModel(
            name='Paradigm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('part_of_speech', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paradigms', to='languages.language')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ParadigmCell',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.CharField(max_length=100)),
                ('grammatical_signature', models.JSONField()),
                ('notes', models.TextField(blank=True)),
                ('paradigm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='morphology.paradigm')),
            ],
            options={
                'ordering': ['form'],
            },
        ),
        migrations.CreateModel(
            name='InflectionValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('abbreviation', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='morphology.inflectioncategory')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
