# Generated by Django 6.0.3 on 2026-04-02 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phoneme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipa', models.CharField(max_length=50)),
                ('phoneme_type', models.CharField(choices=[('vowel', 'Vowel'), ('consonant', 'Consonant')], max_length=20)),
                ('voicing', models.CharField(blank=True, max_length=50)),
                ('place', models.CharField(blank=True, max_length=50)),
                ('manner', models.CharField(blank=True, max_length=50)),
                ('height', models.CharField(blank=True, max_length=50)),
                ('backness', models.CharField(blank=True, max_length=50)),
                ('rounded', models.BooleanField(blank=True, null=True)),
                ('nasal', models.BooleanField(default=False)),
                ('length', models.CharField(blank=True, max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonemes', to='languages.language')),
            ],
            options={
                'ordering': ['ipa'],
                'unique_together': {('language', 'ipa')},
            },
        ),
        migrations.CreateModel(
            name='Allophone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ipa', models.CharField(max_length=50)),
                ('environment', models.TextField()),
                ('description', models.TextField(blank=True)),
                ('phoneme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allophones', to='phonology.phoneme')),
            ],
            options={
                'ordering': ['ipa'],
            },
        ),
        migrations.CreateModel(
            name='PhonotacticRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('allowed_pattern', models.CharField(max_length=100)),
                ('forbidden_pattern', models.CharField(blank=True, max_length=100)),
                ('position', models.CharField(blank=True, max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phonotactic_rules', to='languages.language')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SoundChangeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('input_pattern', models.CharField(max_length=100)),
                ('output_pattern', models.CharField(max_length=100)),
                ('environment', models.CharField(blank=True, max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sound_changes', to='languages.language')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SyllablePattern',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pattern', models.CharField(max_length=50)),
                ('is_common', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='syllable_patterns', to='languages.language')),
            ],
            options={
                'ordering': ['pattern'],
                'unique_together': {('language', 'pattern')},
            },
        ),
    ]
