# Generated by Django 6.0.3 on 2026-04-02 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('morphology', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expression', models.CharField(max_length=255)),
                ('meaning', models.TextField(blank=True)),
                ('grammatical_pattern', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collocations', to='languages.language')),
            ],
            options={
                'ordering': ['expression'],
            },
        ),
        migrations.CreateModel(
            name='IdiomExpression',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expression', models.CharField(max_length=255)),
                ('literal_meaning', models.TextField(blank=True)),
                ('idiomatic_meaning', models.TextField()),
                ('usage_notes', models.TextField(blank=True)),
                ('register', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiom_expressions', to='languages.language')),
            ],
            options={
                'ordering': ['expression'],
            },
        ),
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lemma', models.CharField(max_length=255)),
                ('canonical_form', models.CharField(blank=True, max_length=255)),
                ('romanized_form', models.CharField(blank=True, max_length=255)),
                ('phonemic_form', models.CharField(blank=True, max_length=255)),
                ('phonetic_form', models.CharField(blank=True, max_length=255)),
                ('etymology_summary', models.TextField(blank=True)),
                ('meaning_core', models.CharField(blank=True, max_length=255)),
                ('usage_notes', models.TextField(blank=True)),
                ('frequency_level', models.CharField(blank=True, max_length=50)),
                ('register', models.CharField(blank=True, max_length=50)),
                ('transitivity', models.CharField(blank=True, max_length=30)),
                ('animacy_class', models.CharField(blank=True, max_length=50)),
                ('classifier_type', models.CharField(blank=True, max_length=50)),
                ('irregular', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lexemes', to='languages.language')),
                ('root_morpheme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lexemes', to='morphology.morpheme')),
            ],
            options={
                'ordering': ['lemma'],
            },
        ),
        migrations.CreateModel(
            name='LexemeForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('form', models.CharField(max_length=255)),
                ('form_type', models.CharField(choices=[('base', 'Base'), ('inflected', 'Inflected'), ('derived', 'Derived'), ('variant', 'Variant')], default='base', max_length=20)),
                ('phonological_form', models.CharField(blank=True, max_length=255)),
                ('orthographic_form', models.CharField(blank=True, max_length=255)),
                ('grammatical_signature', models.JSONField(blank=True, default=dict)),
                ('is_irregular', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='lexicon.lexeme')),
            ],
            options={
                'ordering': ['form'],
            },
        ),
        migrations.CreateModel(
            name='LexemeRelation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relation_type', models.CharField(choices=[('synonym', 'Synonym'), ('antonym', 'Antonym'), ('hypernym', 'Hypernym'), ('hyponym', 'Hyponym'), ('meronym', 'Meronym'), ('holonym', 'Holonym'), ('derived_from', 'Derived From'), ('cognate_of', 'Cognate Of'), ('variant_of', 'Variant Of'), ('related_to', 'Related To')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('source_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relations', to='lexicon.lexeme')),
                ('target_lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relations', to='lexicon.lexeme')),
            ],
            options={
                'ordering': ['relation_type'],
            },
        ),
        migrations.CreateModel(
            name='PartOfSpeech',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('is_open_class', models.BooleanField(default=True)),
                ('inflects', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts_of_speech', to='languages.language')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('language', 'code')},
            },
        ),
        migrations.AddField(
            model_name='lexeme',
            name='part_of_speech',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lexemes', to='lexicon.partofspeech'),
        ),
        migrations.CreateModel(
            name='LexemeSense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sense_number', models.PositiveIntegerField(default=1)),
                ('definition', models.TextField()),
                ('semantic_domain', models.CharField(blank=True, max_length=100)),
                ('connotation', models.CharField(blank=True, max_length=50)),
                ('usage_context', models.TextField(blank=True)),
                ('taboo_level', models.CharField(blank=True, max_length=30)),
                ('figurative', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('lexeme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='senses', to='lexicon.lexeme')),
            ],
            options={
                'ordering': ['sense_number'],
                'unique_together': {('lexeme', 'sense_number')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='lexeme',
            unique_together={('language', 'lemma', 'part_of_speech')},
        ),
    ]
