# Generated by Django 6.0.3 on 2026-04-02 17:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('lexicon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorpusText',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('text_type', models.CharField(blank=True, max_length=50)),
                ('content', models.TextField()),
                ('translation', models.TextField(blank=True)),
                ('annotation_level', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corpus_texts', to='languages.language')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CorpusAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token_index', models.PositiveIntegerField()),
                ('token_text', models.CharField(max_length=255)),
                ('lemma', models.CharField(blank=True, max_length=255)),
                ('part_of_speech', models.CharField(blank=True, max_length=100)),
                ('morphology', models.JSONField(blank=True, default=dict)),
                ('syntax', models.JSONField(blank=True, default=dict)),
                ('semantics', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('corpus_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='corpus.corpustext')),
            ],
            options={
                'ordering': ['token_index'],
            },
        ),
        migrations.CreateModel(
            name='ExampleSentence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text_native', models.TextField()),
                ('text_romanized', models.TextField(blank=True)),
                ('phonemic_transcription', models.TextField(blank=True)),
                ('phonetic_transcription', models.TextField(blank=True)),
                ('gloss_line', models.TextField(blank=True)),
                ('free_translation', models.TextField(blank=True)),
                ('literal_translation', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('generated', 'Generated'), ('corpus', 'Corpus')], default='manual', max_length=20)),
                ('difficulty_level', models.CharField(blank=True, max_length=50)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='example_sentences', to='languages.language')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_text', models.TextField()),
                ('target_text', models.TextField()),
                ('source_language_name', models.CharField(max_length=100)),
                ('target_language_name', models.CharField(max_length=100)),
                ('translation_type', models.CharField(choices=[('literal', 'Literal'), ('free', 'Free'), ('adapted', 'Adapted'), ('scholarly', 'Scholarly')], default='free', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='languages.language')),
            ],
            options={
                'ordering': ['source_language_name', 'target_language_name'],
            },
        ),
        migrations.CreateModel(
            name='ExampleSentenceWord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.PositiveIntegerField()),
                ('surface_form', models.CharField(max_length=255)),
                ('gloss', models.CharField(blank=True, max_length=255)),
                ('grammatical_info', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('example_sentence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='corpus.examplesentence')),
                ('lexeme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='example_occurrences', to='lexicon.lexeme')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('example_sentence', 'position')},
            },
        ),
    ]
