# Generated by Django 6.0.3 on 2026-04-02 17:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('native_name', models.CharField(blank=True, max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('full_description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('deprecated', 'Deprecated'), ('archived', 'Archived')], max_length=20)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public')], max_length=10)),
                ('language_type', models.CharField(blank=True, max_length=50)),
                ('inspiration_notes', models.TextField(blank=True)),
                ('primary_word_order', models.CharField(blank=True, max_length=10)),
                ('morphological_type', models.CharField(blank=True, max_length=50)),
                ('alignment_type', models.CharField(blank=True, max_length=50)),
                ('canonical_writing_direction', models.CharField(blank=True, max_length=10)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='projects.project')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LanguageMetadata',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fictional_region', models.CharField(blank=True, max_length=255)),
                ('real_world_influences', models.TextField(blank=True)),
                ('cultural_notes', models.TextField(blank=True)),
                ('historical_notes', models.TextField(blank=True)),
                ('phonological_notes', models.TextField(blank=True)),
                ('grammatical_notes', models.TextField(blank=True)),
                ('estimated_speakers', models.IntegerField(blank=True, null=True)),
                ('difficulty_level', models.CharField(blank=True, max_length=50)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('language', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metadata', to='languages.language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dialect',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('region', models.CharField(blank=True, max_length=255)),
                ('social_group', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('mutual_intelligibility_notes', models.TextField(blank=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dialects', to='languages.language')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('language', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='LanguageStage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField()),
                ('stage_order', models.IntegerField()),
                ('period_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_active_stage', models.BooleanField(default=False)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='languages.language')),
            ],
            options={
                'ordering': ['stage_order'],
                'unique_together': {('language', 'slug')},
            },
        ),
    ]
